name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request: {}

jobs:
  test:
    strategy:
      matrix:
        dc: [dmd-latest, ldc-latest]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: ~/.dub
          key: ${{ runner.os }}-dub-${{ matrix.dc }}-${{ hashFiles('**/dub.json') }}
      - uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: |
          if [ -e dub.json -o -e dub.sdl ]; then
            dub test
          fi
